Procedures to build the ooh323c stack

Windows using Visual Studio

To build the libraries on Windows using Visual Studio, the 'nmake'
utility is used.  Change directory to each of the build_* directories
and execute nmake to build the libraries from source.

Compiler options can be changed by editing the platform.mk file in
the root directory.

Include file dependencies can be generated by executing the mkdepend.pl
perl script in the src directory.

The build.pl script in the root directory can be executed to build all
debug and/or release libraries.


Linux/UNIX

To build the libraries and test programs on Linux/UNIX, the cmake
utility program is used (http://www.cmake.org).  The procedure is
as follows:

1. cd to the ooh323c root directory

2. Execute 'cmake .' (don't forget the dot!).  This will generate all
required makefiles.

3. Execute 'make'

For example (assuming the version number is 0.9.1):

cd ooh323c-0.9.1
cmake .
make

