OOH323COBJS=$(OOH323C_OBJDIR)/context.obj\
$(OOH323C_OBJDIR)/decode.obj\
$(OOH323C_OBJDIR)/dlist.obj\
$(OOH323C_OBJDIR)/encode.obj\
$(OOH323C_OBJDIR)/errmgmt.obj\
$(OOH323C_OBJDIR)/eventHandler.obj\
$(OOH323C_OBJDIR)/memheap.obj\
$(OOH323C_OBJDIR)/ooCalls.obj\
$(OOH323C_OBJDIR)/ooCapability.obj\
$(OOH323C_OBJDIR)/oochannels.obj\
$(OOH323C_OBJDIR)/ooDateTime.obj\
$(OOH323C_OBJDIR)/ooGkClient.obj\
$(OOH323C_OBJDIR)/ooh245.obj\
$(OOH323C_OBJDIR)/ooh323.obj\
$(OOH323C_OBJDIR)/ooh323ep.obj\
$(OOH323C_OBJDIR)/ooLogChan.obj\
$(OOH323C_OBJDIR)/ooports.obj\
$(OOH323C_OBJDIR)/ooq931.obj\
$(OOH323C_OBJDIR)/ooSocket.obj\
$(OOH323C_OBJDIR)/ooStackCmds.obj\
$(OOH323C_OBJDIR)/ooTimer.obj\
$(OOH323C_OBJDIR)/ootrace.obj\
$(OOH323C_OBJDIR)/ooUtils.obj\
$(OOH323C_OBJDIR)/perutil.obj\
$(OOH323C_OBJDIR)/printHandler.obj\
$(OOH323C_OBJDIR)/rtctype.obj\
$(OOH323C_OBJDIR)/H323-MESSAGES.obj\
$(OOH323C_OBJDIR)/H323-MESSAGESDec.obj\
$(OOH323C_OBJDIR)/H323-MESSAGESEnc.obj\
$(OOH323C_OBJDIR)/H235-SECURITY-MESSAGESDec.obj\
$(OOH323C_OBJDIR)/H235-SECURITY-MESSAGESEnc.obj\
$(OOH323C_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROL.obj\
$(OOH323C_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLDec.obj\
$(OOH323C_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLEnc.obj

OOH323COBJS_A=$(OOH323CA_OBJDIR)/context.obj\
$(OOH323CA_OBJDIR)/decode.obj\
$(OOH323CA_OBJDIR)/dlist.obj\
$(OOH323CA_OBJDIR)/encode.obj\
$(OOH323CA_OBJDIR)/errmgmt.obj\
$(OOH323CA_OBJDIR)/eventHandler.obj\
$(OOH323CA_OBJDIR)/memheap.obj\
$(OOH323CA_OBJDIR)/ooCalls.obj\
$(OOH323CA_OBJDIR)/ooCapability.obj\
$(OOH323CA_OBJDIR)/oochannels.obj\
$(OOH323CA_OBJDIR)/ooDateTime.obj\
$(OOH323CA_OBJDIR)/ooGkClient.obj\
$(OOH323CA_OBJDIR)/ooh245.obj\
$(OOH323CA_OBJDIR)/ooh323.obj\
$(OOH323CA_OBJDIR)/ooh323ep.obj\
$(OOH323CA_OBJDIR)/ooLogChan.obj\
$(OOH323CA_OBJDIR)/ooports.obj\
$(OOH323CA_OBJDIR)/ooq931.obj\
$(OOH323CA_OBJDIR)/ooSocket.obj\
$(OOH323CA_OBJDIR)/ooStackCmds.obj\
$(OOH323CA_OBJDIR)/ooTimer.obj\
$(OOH323CA_OBJDIR)/ootrace.obj\
$(OOH323CA_OBJDIR)/ooUtils.obj\
$(OOH323CA_OBJDIR)/perutil.obj\
$(OOH323CA_OBJDIR)/printHandler.obj\
$(OOH323CA_OBJDIR)/rtctype.obj\
$(OOH323CA_OBJDIR)/H323-MESSAGES.obj\
$(OOH323CA_OBJDIR)/H323-MESSAGESDec.obj\
$(OOH323CA_OBJDIR)/H323-MESSAGESEnc.obj\
$(OOH323CA_OBJDIR)/H235-SECURITY-MESSAGESDec.obj\
$(OOH323CA_OBJDIR)/H235-SECURITY-MESSAGESEnc.obj\
$(OOH323CA_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROL.obj\
$(OOH323CA_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLDec.obj\
$(OOH323CA_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLEnc.obj

OOH323COBJSD=$(OOH323CD_OBJDIR)/context.obj\
$(OOH323CD_OBJDIR)/decode.obj\
$(OOH323CD_OBJDIR)/dlist.obj\
$(OOH323CD_OBJDIR)/encode.obj\
$(OOH323CD_OBJDIR)/errmgmt.obj\
$(OOH323CD_OBJDIR)/eventHandler.obj\
$(OOH323CD_OBJDIR)/memheap.obj\
$(OOH323CD_OBJDIR)/ooCalls.obj\
$(OOH323CD_OBJDIR)/ooCapability.obj\
$(OOH323CD_OBJDIR)/oochannels.obj\
$(OOH323CD_OBJDIR)/ooDateTime.obj\
$(OOH323CD_OBJDIR)/ooGkClient.obj\
$(OOH323CD_OBJDIR)/ooh245.obj\
$(OOH323CD_OBJDIR)/ooh323.obj\
$(OOH323CD_OBJDIR)/ooh323ep.obj\
$(OOH323CD_OBJDIR)/ooLogChan.obj\
$(OOH323CD_OBJDIR)/ooports.obj\
$(OOH323CD_OBJDIR)/ooq931.obj\
$(OOH323CD_OBJDIR)/ooSocket.obj\
$(OOH323CD_OBJDIR)/ooStackCmds.obj\
$(OOH323CD_OBJDIR)/ooTimer.obj\
$(OOH323CD_OBJDIR)/ootrace.obj\
$(OOH323CD_OBJDIR)/ooUtils.obj\
$(OOH323CD_OBJDIR)/perutil.obj\
$(OOH323CD_OBJDIR)/printHandler.obj\
$(OOH323CD_OBJDIR)/rtctype.obj\
$(OOH323CD_OBJDIR)/H323-MESSAGES.obj\
$(OOH323CD_OBJDIR)/H323-MESSAGESDec.obj\
$(OOH323CD_OBJDIR)/H323-MESSAGESEnc.obj\
$(OOH323CD_OBJDIR)/H235-SECURITY-MESSAGESDec.obj\
$(OOH323CD_OBJDIR)/H235-SECURITY-MESSAGESEnc.obj\
$(OOH323CD_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROL.obj\
$(OOH323CD_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLDec.obj\
$(OOH323CD_OBJDIR)/MULTIMEDIA-SYSTEM-CONTROLEnc.obj


OOMEDIAOBJS=$(OOMEDIA_OBJDIR)/g711.obj\
$(OOMEDIA_OBJDIR)/ooCommon.obj\
$(OOMEDIA_OBJDIR)/oortp.obj\
$(OOMEDIA_OBJDIR)/ooSock.obj\
$(OOMEDIA_OBJDIR)/ooWave.obj

OOMEDIAOBJSD=$(OOMEDIAD_OBJDIR)/g711.obj\
$(OOMEDIAD_OBJDIR)/ooCommon.obj\
$(OOMEDIAD_OBJDIR)/oortp.obj\
$(OOMEDIAD_OBJDIR)/ooSock.obj\
$(OOMEDIAD_OBJDIR)/ooWave.obj


OOSIMPLEOBJS=$(OOSIMPLE_OBJDIR)/simple.obj\
$(OOSIMPLE_OBJDIR)/oosndrtp.obj

OOSIMPLEOBJSD=$(OOSIMPLED_OBJDIR)/simple.obj\
$(OOSIMPLED_OBJDIR)/oosndrtp.obj

OOPLAYEROBJS=$(OOPLAYER_OBJDIR)/ooPlayer.obj\
$(OOPLAYER_OBJDIR)/oosndrtp.obj

OOPLAYEROBJSD=$(OOPLAYERD_OBJDIR)/ooPlayer.obj\
$(OOPLAYERD_OBJDIR)/oosndrtp.obj

OORECEIVEROBJS=$(OORECEIVER_OBJDIR)/ooReceiver.obj\
$(OORECEIVER_OBJDIR)/oosndrtp.obj

OORECEIVEROBJSD=$(OORECEIVERD_OBJDIR)/ooReceiver.obj\
$(OORECEIVERD_OBJDIR)/oosndrtp.obj

OOH323PEEROBJS=$(OOH323PEER_OBJDIR)/h323peer.obj

OOH323PEEROBJSD=$(OOH323PEERD_OBJDIR)/h323peer.obj
