/*
 * Copyright (C) 1997-2009 by Objective Systems, Inc.
 *
 * This software is furnished under an open source license and may be
 * used and copied only in accordance with the terms of this license.
 * The text of the license may generally be found in the root
 * directory of this installation in the COPYING file.  It
 * can also be viewed online at the following URL:
 *
 *   http://www.obj-sys.com/open/license.html
 *
 * Any redistributions of this file including modified versions must
 * maintain this copyright notice.
 *
 *****************************************************************************/
/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.2.B, Date: 06-Apr-2009.
 */
#include "H323-MESSAGES.h"
#include "ooCommon.h"

static const OOEnumItem H225ScreeningIndicator_ENUMTAB[] = {
   { "networkProvided", 3, 15, 1 },
   { "userProvidedNotScreened", 0, 23, 3 },
   { "userProvidedVerifiedAndFailed", 2, 29, 2 },
   { "userProvidedVerifiedAndPassed", 1, 29, 0 }
} ;
#define H225ScreeningIndicator_ENUMTABSIZE 4

const char* H225ScreeningIndicator_ToString (OOINT32 value)
{
   OOINT32 idx = value;

   if (idx >= 0 && idx < H225ScreeningIndicator_ENUMTABSIZE) {
      return H225ScreeningIndicator_ENUMTAB
         [H225ScreeningIndicator_ENUMTAB[idx].transidx].name;
   }
   else
      return "_UNKNOWN_";
}

int H225ScreeningIndicator_ToEnum (OOCTXT* pctxt,
   const char* value, H225ScreeningIndicator* pvalue)
{
   OOUINT32 valueLen = strlen (value);
   OOINT32 idx = lookupEnum (value, valueLen,
      H225ScreeningIndicator_ENUMTAB, H225ScreeningIndicator_ENUMTABSIZE);

   if (idx >= 0) {
      *pvalue = (H225ScreeningIndicator)
         H225ScreeningIndicator_ENUMTAB[idx].value;
      return 0;
   }
   else {
      return ASN_E_INVENUM;
   }
}

EXTERN const char* gs_H323_MESSAGES_NumberDigits_CharSet =
"#*,0123456789";

EXTERN const char* gs_H323_MESSAGES_TBCD_STRING_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_IsupDigits_CharSet =
"0123456789ABCDE";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_system_id_sid_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_system_id_mid_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_imsi_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_min_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_mdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_msisdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_esn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_mscid_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_sesn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_soc_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_imsi_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_msisdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_imei_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_hplmn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_vplmn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_AliasAddress_dialedDigits_CharSet =
"#*,0123456789";

