/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 5.72, Date: 22-Mar-2005.
 */
#include "ooasn1.h"
#include "H323-MESSAGES.h"

/**************************************************************/
/*                                                            */
/*  NumberDigits                                              */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_NumberDigits_CharSet =
"#*,0123456789";

/**************************************************************/
/*                                                            */
/*  TBCD_STRING                                               */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_TBCD_STRING_CharSet =
"#*0123456789abc";

/**************************************************************/
/*                                                            */
/*  ANSI_41_UIM_system_id                                     */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_system_id_sid_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_system_id_mid_CharSet =
"#*0123456789abc";

/**************************************************************/
/*                                                            */
/*  ANSI_41_UIM                                               */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_imsi_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_min_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_mdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_msisdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_esn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_mscid_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_sesn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_ANSI_41_UIM_soc_CharSet =
"#*0123456789abc";

/**************************************************************/
/*                                                            */
/*  GSM_UIM                                                   */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_imsi_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_msisdn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_imei_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_hplmn_CharSet =
"#*0123456789abc";

EXTERN const char* gs_H323_MESSAGES_GSM_UIM_vplmn_CharSet =
"#*0123456789abc";

/**************************************************************/
/*                                                            */
/*  AliasAddress                                              */
/*                                                            */
/**************************************************************/

EXTERN const char* gs_H323_MESSAGES_AliasAddress_dialedDigits_CharSet =
"#*,0123456789";

