COMMON_OBJECTS = \
context$(OBJ) \
decode$(OBJ) \
dlist$(OBJ) \
encode$(OBJ) \
errmgmt$(OBJ) \
eventHandler$(OBJ) \
memheap$(OBJ) \
ooCalls$(OBJ) \
ooCapability$(OBJ) \
ooCmdChannel$(OBJ) \
ooConfig$(OBJ) \
ooDateTime$(OBJ) \
ooGkClient$(OBJ) \
ooLogChan$(OBJ) \
ooSocket$(OBJ) \
ooStackCmds$(OBJ) \
ooTimer$(OBJ) \
ooUtils$(OBJ) \
oochannels$(OBJ) \
ooh245$(OBJ) \
ooh323$(OBJ) \
ooh323ep$(OBJ) \
ooports$(OBJ) \
ooq931$(OBJ) \
ootrace$(OBJ) \
perutil$(OBJ) \
printHandler$(OBJ) \
rtctype$(OBJ)
